version: '3.8'

services:
  rust-app:
    build: .
    image: my-rust-app:ubuntu20.04
    restart: unless-stopped
    volumes:
      - ./target:/usr/src/app/target
      - ./src:/usr/src/app/src
      - ./release:/app
    environment:
      - DATABASE_URL="mysql://root:root@localhost/versioning?ssl-mode=DISABLED"
      - MAX_LOG_LEVEL=DEBUG
      - KIOSK_DIRECTORY=/Users/aditya/Documents/kiosk
      - KIOSK_DOWNLOADABLE_URL=http://localhost:3000
      - APP_URL=0.0.0.0:3000
